"""empty message

Revision ID: 5074e0fd4f65
Revises: 
Create Date: 2022-07-08 14:56:23.192570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5074e0fd4f65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ItemsCategory',
    sa.Column('ItemCatID', sa.Integer(), nullable=False),
    sa.Column('ItemCatDesc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ItemCatID')
    )
    op.create_table('user_tbl',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(), nullable=False),
    sa.Column('pwd', sa.String(), nullable=False),
    sa.Column('userType', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_table('ItemMaster',
    sa.Column('ItemID', sa.Integer(), nullable=False),
    sa.Column('ItemCatID', sa.Integer(), nullable=False),
    sa.Column('ItemDesc', sa.String(), nullable=False),
    sa.Column('AvailAmt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ItemCatID'], ['ItemsCategory.ItemCatID'], ),
    sa.PrimaryKeyConstraint('ItemID')
    )
    op.create_table('AddItems',
    sa.Column('transID', sa.Integer(), nullable=False),
    sa.Column('ItemID', sa.Integer(), nullable=False),
    sa.Column('AddQty', sa.Integer(), nullable=False),
    sa.Column('AddDate', sa.Date(), nullable=False),
    sa.Column('VendorName', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ItemID'], ['ItemMaster.ItemID'], ),
    sa.PrimaryKeyConstraint('transID')
    )
    op.create_table('request_tbl',
    sa.Column('reqID', sa.Integer(), nullable=False),
    sa.Column('ReqDeptt', sa.String(), nullable=False),
    sa.Column('ReqDate', sa.Date(), nullable=False),
    sa.Column('ItemID', sa.Integer(), nullable=False),
    sa.Column('ReqQty', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.String(), nullable=False),
    sa.Column('issueDate', sa.Date(), nullable=False),
    sa.Column('returnDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ItemID'], ['ItemMaster.ItemID'], ),
    sa.ForeignKeyConstraint(['userID'], ['user_tbl.userID'], ),
    sa.PrimaryKeyConstraint('reqID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_tbl')
    op.drop_table('AddItems')
    op.drop_table('ItemMaster')
    op.drop_table('user_tbl')
    op.drop_table('ItemsCategory')
    # ### end Alembic commands ###
